//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: solana_stablecoin_standard
// ----------------------------------------------------------------------------
pub mod solana_stablecoin_standard {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for solana_stablecoin_standard
    pub fn program_id() -> Pubkey {
        pubkey!("5uWfEyXtYh6gFicfTCQjfWhe9ENmggxaf7DG3ffbjK6y")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: Initialize
    // ....................................................................

    /// Main instruction struct for Initialize
    pub struct InitializeInstruction {
        pub accounts: InitializeInstructionAccountMetas,
        pub data: InitializeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Initialize instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeInstructionAccountMetas {}

    /// Account pubkeys for Initialize instruction
    #[derive(Debug, Clone)]
    pub struct InitializeInstructionAccounts {}

    impl InitializeInstructionAccounts {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Instruction data for Initialize
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeInstructionData {}

    impl InitializeInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for InitializeInstruction
    impl InitializeInstruction {
        fn discriminator() -> [u8; 8] {
            [175u8, 175u8, 109u8, 31u8, 13u8, 152u8, 155u8, 237u8]
        }

        pub fn data(data: InitializeInstructionData) -> Self {
            Self {
                accounts: InitializeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeInstructionAccounts) -> Self {
            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ----------------------------------------------------------------------------
// Program: manager
// ----------------------------------------------------------------------------
pub mod manager {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for manager
    pub fn program_id() -> Pubkey {
        pubkey!("11111111111111111111111111111111")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: Initialize
    // ....................................................................

    /// Main instruction struct for Initialize
    pub struct InitializeInstruction {
        pub accounts: InitializeInstructionAccountMetas,
        pub data: InitializeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Initialize instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeInstructionAccountMetas {
        pub master_authority: AccountMeta,

        pub mint: AccountMeta,

        pub config: AccountMeta,

        pub system_program: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for Initialize instruction
    #[derive(Debug, Clone)]
    pub struct InitializeInstructionAccounts {
        pub master_authority: Pubkey,

        pub mint: Pubkey,

        pub config: Pubkey,
    }

    impl InitializeInstructionAccounts {
        pub fn new(master_authority: Pubkey, mint: Pubkey, config: Pubkey) -> Self {
            Self {
                master_authority,

                mint,

                config,
            }
        }
    }

    /// Instruction data for Initialize
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeInstructionData {
        pub params: InitParams,
    }

    impl InitializeInstructionData {
        pub fn new(params: InitParams) -> Self {
            Self { params }
        }
    }

    /// Implementation for InitializeInstruction
    impl InitializeInstruction {
        fn discriminator() -> [u8; 8] {
            [175u8, 175u8, 109u8, 31u8, 13u8, 152u8, 155u8, 237u8]
        }

        pub fn data(data: InitializeInstructionData) -> Self {
            Self {
                accounts: InitializeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeInstructionAccounts) -> Self {
            self.accounts.master_authority = AccountMeta::new(accounts.master_authority, true);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.master_authority.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: MintTokens
    // ....................................................................

    /// Main instruction struct for MintTokens
    pub struct MintTokensInstruction {
        pub accounts: MintTokensInstructionAccountMetas,
        pub data: MintTokensInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for MintTokens instruction
    #[derive(Debug, Clone, Default)]
    pub struct MintTokensInstructionAccountMetas {
        pub minter: AccountMeta,

        pub config: AccountMeta,

        pub minter_record: AccountMeta,

        pub mint: AccountMeta,

        pub destination: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for MintTokens instruction
    #[derive(Debug, Clone)]
    pub struct MintTokensInstructionAccounts {
        pub minter: Pubkey,

        pub config: Pubkey,

        pub minter_record: Pubkey,

        pub mint: Pubkey,

        pub destination: Pubkey,
    }

    impl MintTokensInstructionAccounts {
        pub fn new(
            minter: Pubkey,

            config: Pubkey,

            minter_record: Pubkey,

            mint: Pubkey,

            destination: Pubkey,
        ) -> Self {
            Self {
                minter,

                config,

                minter_record,

                mint,

                destination,
            }
        }
    }

    /// Instruction data for MintTokens
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct MintTokensInstructionData {
        pub amount: u64,
    }

    impl MintTokensInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for MintTokensInstruction
    impl MintTokensInstruction {
        fn discriminator() -> [u8; 8] {
            [59u8, 132u8, 24u8, 246u8, 122u8, 39u8, 8u8, 243u8]
        }

        pub fn data(data: MintTokensInstructionData) -> Self {
            Self {
                accounts: MintTokensInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: MintTokensInstructionAccounts) -> Self {
            self.accounts.minter = AccountMeta::new(accounts.minter, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.minter_record = AccountMeta::new(accounts.minter_record, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.destination = AccountMeta::new(accounts.destination, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.minter.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.minter_record.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.destination.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: RegisterMinter
    // ....................................................................

    /// Main instruction struct for RegisterMinter
    pub struct RegisterMinterInstruction {
        pub accounts: RegisterMinterInstructionAccountMetas,
        pub data: RegisterMinterInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for RegisterMinter instruction
    #[derive(Debug, Clone, Default)]
    pub struct RegisterMinterInstructionAccountMetas {
        pub minter_admin: AccountMeta,

        pub config: AccountMeta,

        pub minter_record: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for RegisterMinter instruction
    #[derive(Debug, Clone)]
    pub struct RegisterMinterInstructionAccounts {
        pub minter_admin: Pubkey,

        pub config: Pubkey,

        pub minter_record: Pubkey,
    }

    impl RegisterMinterInstructionAccounts {
        pub fn new(minter_admin: Pubkey, config: Pubkey, minter_record: Pubkey) -> Self {
            Self {
                minter_admin,

                config,

                minter_record,
            }
        }
    }

    /// Instruction data for RegisterMinter
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct RegisterMinterInstructionData {
        pub minter_pubkey: Pubkey,

        pub quota: u64,
    }

    impl RegisterMinterInstructionData {
        pub fn new(minter_pubkey: Pubkey, quota: u64) -> Self {
            Self {
                minter_pubkey,

                quota,
            }
        }
    }

    /// Implementation for RegisterMinterInstruction
    impl RegisterMinterInstruction {
        fn discriminator() -> [u8; 8] {
            [58u8, 224u8, 74u8, 142u8, 170u8, 95u8, 116u8, 191u8]
        }

        pub fn data(data: RegisterMinterInstructionData) -> Self {
            Self {
                accounts: RegisterMinterInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: RegisterMinterInstructionAccounts) -> Self {
            self.accounts.minter_admin = AccountMeta::new(accounts.minter_admin, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.minter_record = AccountMeta::new(accounts.minter_record, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.minter_admin.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.minter_record.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Seize
    // ....................................................................

    /// Main instruction struct for Seize
    pub struct SeizeInstruction {
        pub accounts: SeizeInstructionAccountMetas,
        pub data: SeizeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Seize instruction
    #[derive(Debug, Clone, Default)]
    pub struct SeizeInstructionAccountMetas {
        pub seizer: AccountMeta,

        pub config: AccountMeta,

        pub mint: AccountMeta,

        pub target_account: AccountMeta,

        pub treasury_account: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for Seize instruction
    #[derive(Debug, Clone)]
    pub struct SeizeInstructionAccounts {
        pub seizer: Pubkey,

        pub config: Pubkey,

        pub mint: Pubkey,

        pub target_account: Pubkey,

        pub treasury_account: Pubkey,
    }

    impl SeizeInstructionAccounts {
        pub fn new(
            seizer: Pubkey,

            config: Pubkey,

            mint: Pubkey,

            target_account: Pubkey,

            treasury_account: Pubkey,
        ) -> Self {
            Self {
                seizer,

                config,

                mint,

                target_account,

                treasury_account,
            }
        }
    }

    /// Instruction data for Seize
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SeizeInstructionData {
        pub amount: u64,
    }

    impl SeizeInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for SeizeInstruction
    impl SeizeInstruction {
        fn discriminator() -> [u8; 8] {
            [129u8, 159u8, 143u8, 31u8, 161u8, 224u8, 241u8, 84u8]
        }

        pub fn data(data: SeizeInstructionData) -> Self {
            Self {
                accounts: SeizeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SeizeInstructionAccounts) -> Self {
            self.accounts.seizer = AccountMeta::new(accounts.seizer, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.target_account = AccountMeta::new(accounts.target_account, false);

            self.accounts.treasury_account = AccountMeta::new(accounts.treasury_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.seizer.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.target_account.clone());

            metas.push(self.accounts.treasury_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ----------------------------------------------------------------------------
// Program: compliance_hook
// ----------------------------------------------------------------------------
pub mod compliance_hook {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for compliance_hook
    pub fn program_id() -> Pubkey {
        pubkey!("Fg6PaFpoGXkYsidMpWxTWqkZq6yY4xXv5b2K6hC4QGkA")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: AddToBlacklist
    // ....................................................................

    /// Main instruction struct for AddToBlacklist
    pub struct AddToBlacklistInstruction {
        pub accounts: AddToBlacklistInstructionAccountMetas,
        pub data: AddToBlacklistInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for AddToBlacklist instruction
    #[derive(Debug, Clone, Default)]
    pub struct AddToBlacklistInstructionAccountMetas {
        pub admin: AccountMeta,

        pub config: AccountMeta,

        pub target_wallet: AccountMeta,

        pub blacklist_record: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for AddToBlacklist instruction
    #[derive(Debug, Clone)]
    pub struct AddToBlacklistInstructionAccounts {
        pub admin: Pubkey,

        pub config: Pubkey,

        pub target_wallet: Pubkey,

        pub blacklist_record: Pubkey,
    }

    impl AddToBlacklistInstructionAccounts {
        pub fn new(
            admin: Pubkey,

            config: Pubkey,

            target_wallet: Pubkey,

            blacklist_record: Pubkey,
        ) -> Self {
            Self {
                admin,

                config,

                target_wallet,

                blacklist_record,
            }
        }
    }

    /// Instruction data for AddToBlacklist
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct AddToBlacklistInstructionData {
        pub reason: String,
    }

    impl AddToBlacklistInstructionData {
        pub fn new(reason: String) -> Self {
            Self { reason }
        }
    }

    /// Implementation for AddToBlacklistInstruction
    impl AddToBlacklistInstruction {
        fn discriminator() -> [u8; 8] {
            [90u8, 115u8, 98u8, 231u8, 173u8, 119u8, 117u8, 176u8]
        }

        pub fn data(data: AddToBlacklistInstructionData) -> Self {
            Self {
                accounts: AddToBlacklistInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: AddToBlacklistInstructionAccounts) -> Self {
            self.accounts.admin = AccountMeta::new(accounts.admin, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.target_wallet = AccountMeta::new_readonly(accounts.target_wallet, false);

            self.accounts.blacklist_record = AccountMeta::new(accounts.blacklist_record, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.target_wallet.clone());

            metas.push(self.accounts.blacklist_record.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: RemoveFromBlacklist
    // ....................................................................

    /// Main instruction struct for RemoveFromBlacklist
    pub struct RemoveFromBlacklistInstruction {
        pub accounts: RemoveFromBlacklistInstructionAccountMetas,
        pub data: RemoveFromBlacklistInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for RemoveFromBlacklist instruction
    #[derive(Debug, Clone, Default)]
    pub struct RemoveFromBlacklistInstructionAccountMetas {
        pub admin: AccountMeta,

        pub config: AccountMeta,

        pub target_wallet: AccountMeta,

        pub blacklist_record: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for RemoveFromBlacklist instruction
    #[derive(Debug, Clone)]
    pub struct RemoveFromBlacklistInstructionAccounts {
        pub admin: Pubkey,

        pub config: Pubkey,

        pub target_wallet: Pubkey,

        pub blacklist_record: Pubkey,
    }

    impl RemoveFromBlacklistInstructionAccounts {
        pub fn new(
            admin: Pubkey,

            config: Pubkey,

            target_wallet: Pubkey,

            blacklist_record: Pubkey,
        ) -> Self {
            Self {
                admin,

                config,

                target_wallet,

                blacklist_record,
            }
        }
    }

    /// Instruction data for RemoveFromBlacklist
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct RemoveFromBlacklistInstructionData {}

    impl RemoveFromBlacklistInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for RemoveFromBlacklistInstruction
    impl RemoveFromBlacklistInstruction {
        fn discriminator() -> [u8; 8] {
            [47u8, 105u8, 20u8, 10u8, 165u8, 168u8, 203u8, 219u8]
        }

        pub fn data(data: RemoveFromBlacklistInstructionData) -> Self {
            Self {
                accounts: RemoveFromBlacklistInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: RemoveFromBlacklistInstructionAccounts) -> Self {
            self.accounts.admin = AccountMeta::new(accounts.admin, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.target_wallet = AccountMeta::new_readonly(accounts.target_wallet, false);

            self.accounts.blacklist_record = AccountMeta::new(accounts.blacklist_record, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.target_wallet.clone());

            metas.push(self.accounts.blacklist_record.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: TransferHook
    // ....................................................................

    /// Main instruction struct for TransferHook
    pub struct TransferHookInstruction {
        pub accounts: TransferHookInstructionAccountMetas,
        pub data: TransferHookInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for TransferHook instruction
    #[derive(Debug, Clone, Default)]
    pub struct TransferHookInstructionAccountMetas {
        pub source_token: AccountMeta,

        pub mint: AccountMeta,

        pub destination_token: AccountMeta,

        pub owner: AccountMeta,

        pub sender_blacklist_record: AccountMeta,

        pub receiver_blacklist_record: AccountMeta,
    }

    /// Account pubkeys for TransferHook instruction
    #[derive(Debug, Clone)]
    pub struct TransferHookInstructionAccounts {
        pub source_token: Pubkey,

        pub mint: Pubkey,

        pub destination_token: Pubkey,

        pub owner: Pubkey,

        pub sender_blacklist_record: Pubkey,

        pub receiver_blacklist_record: Pubkey,
    }

    impl TransferHookInstructionAccounts {
        pub fn new(
            source_token: Pubkey,

            mint: Pubkey,

            destination_token: Pubkey,

            owner: Pubkey,

            sender_blacklist_record: Pubkey,

            receiver_blacklist_record: Pubkey,
        ) -> Self {
            Self {
                source_token,

                mint,

                destination_token,

                owner,

                sender_blacklist_record,

                receiver_blacklist_record,
            }
        }
    }

    /// Instruction data for TransferHook
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct TransferHookInstructionData {
        pub amount: u64,
    }

    impl TransferHookInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for TransferHookInstruction
    impl TransferHookInstruction {
        fn discriminator() -> [u8; 8] {
            [220u8, 57u8, 220u8, 152u8, 126u8, 125u8, 97u8, 168u8]
        }

        pub fn data(data: TransferHookInstructionData) -> Self {
            Self {
                accounts: TransferHookInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: TransferHookInstructionAccounts) -> Self {
            self.accounts.source_token = AccountMeta::new_readonly(accounts.source_token, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.destination_token =
                AccountMeta::new_readonly(accounts.destination_token, false);

            self.accounts.owner = AccountMeta::new_readonly(accounts.owner, false);

            self.accounts.sender_blacklist_record =
                AccountMeta::new_readonly(accounts.sender_blacklist_record, false);

            self.accounts.receiver_blacklist_record =
                AccountMeta::new_readonly(accounts.receiver_blacklist_record, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.source_token.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.destination_token.clone());

            metas.push(self.accounts.owner.clone());

            metas.push(self.accounts.sender_blacklist_record.clone());

            metas.push(self.accounts.receiver_blacklist_record.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

/// Custom struct: InitParams
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct InitParams {
    pub name: String,

    pub symbol: String,

    pub uri: String,

    pub decimals: u8,

    pub enable_permanent_delegate: bool,

    pub enable_transfer_hook: bool,

    pub default_account_frozen: bool,
}

impl InitParams {
    pub fn new(
        name: String,

        symbol: String,

        uri: String,

        decimals: u8,

        enable_permanent_delegate: bool,

        enable_transfer_hook: bool,

        default_account_frozen: bool,
    ) -> Self {
        Self {
            name,

            symbol,

            uri,

            decimals,

            enable_permanent_delegate,

            enable_transfer_hook,

            default_account_frozen,
        }
    }
}

/// Custom struct: MinterRecord
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct MinterRecord {
    pub minter: Pubkey,

    pub config: Pubkey,

    pub mint_quota: u64,

    pub minted_amount: u64,

    pub is_active: bool,

    pub bump: u8,
}

impl MinterRecord {
    pub fn new(
        minter: Pubkey,

        config: Pubkey,

        mint_quota: u64,

        minted_amount: u64,

        is_active: bool,

        bump: u8,
    ) -> Self {
        Self {
            minter,

            config,

            mint_quota,

            minted_amount,

            is_active,

            bump,
        }
    }
}

/// Custom struct: StablecoinConfig
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct StablecoinConfig {
    pub mint: Pubkey,

    pub master_authority: Pubkey,

    pub minter_admin: Pubkey,

    pub burner_authority: Pubkey,

    pub blacklister_authority: Pubkey,

    pub pauser_authority: Pubkey,

    pub seizer_authority: Pubkey,

    pub enable_permanent_delegate: bool,

    pub enable_transfer_hook: bool,

    pub default_account_frozen: bool,

    pub is_paused: bool,

    pub bump: u8,
}

impl StablecoinConfig {
    pub fn new(
        mint: Pubkey,

        master_authority: Pubkey,

        minter_admin: Pubkey,

        burner_authority: Pubkey,

        blacklister_authority: Pubkey,

        pauser_authority: Pubkey,

        seizer_authority: Pubkey,

        enable_permanent_delegate: bool,

        enable_transfer_hook: bool,

        default_account_frozen: bool,

        is_paused: bool,

        bump: u8,
    ) -> Self {
        Self {
            mint,

            master_authority,

            minter_admin,

            burner_authority,

            blacklister_authority,

            pauser_authority,

            seizer_authority,

            enable_permanent_delegate,

            enable_transfer_hook,

            default_account_frozen,

            is_paused,

            bump,
        }
    }
}

/// Custom struct: BlacklistRecord
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct BlacklistRecord {
    pub is_blacklisted: bool,

    pub reason: String,
}

impl BlacklistRecord {
    pub fn new(is_blacklisted: bool, reason: String) -> Self {
        Self {
            is_blacklisted,

            reason,
        }
    }
}


// ============================================================================
// END OF GENERATED FILE
// ============================================================================
